name: Deploy Web Demo
on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-dev
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pygame-ce board chess tqdm numpy tensorflow==2.12.0 keras==2.12.0
          pip install pygbag
      
      - name: Build with Pygbag
        run: |
          python -m pygbag --build --app_name "Chess Game" --package build --archive .
      
      - name: Ensure index.html is in build
        run: |
          # Copy your index.html to build directory if it's not there
          if [ -f index.html ] && [ ! -f build/index.html ]; then
            cp index.html build/
          fi
          # If index.html exists in root but build has a different name, copy it over
          if [ -f index.html ]; then
            cp index.html build/index.html
          fi
      
      - name: Check build output
        run: |
          ls -la build/
          echo "Contents of index.html:"
          head -10 build/index.html || echo "No index.html found"
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build'

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
